[package]
name = "ecm"
version = "0.1.0"
edition = "2021"
authors = ["skyf0l <skyf0lmails@proton.me>"]
description = "Lenstra's Elliptic Curve Factorization Implementation"
repository = "https://github.com/skyf0l/ecm-rs"
license = "MIT OR Apache-2.0"
categories = ["security", "rsa", "encryption", "crypto", "cryptography"]
keywords = ["rsa", "cracker", "ctf", "crypto", "cryptography"]
include = [
  "src/**/*",
  "Cargo.toml",
  "LICENSE*",
  "README.md",
]
readme = "README.md"

[dependencies]
primal = "0.3"

[dependencies.rug]
version = "1"
default-features = false
features = ["integer", "rand"]
